site_name: 无门之门/蟒营®图书
site_description: 蟒营®系列 Pythonic 实训课程经验总结
site_author: guru101camp@googlegroups.com
site_url: https://d0d.101.camp/
repo_url: https://github.com/101camp/d0d
repo_name: github
copyright: ©101camp 2018-2020 


theme: 
  name: 'simplex'
  custom_dir: '_theme/bootswatch/simplex'
  font: false
  logo: http://101.zoomquiet.top/res/icon/101camp_bauhaus_v3h32.png
  favicon: /img/101camp_bauhaus_v4h420.ico


markdown_extensions:
  - admonition
  - footnotes
  - pymdownx.smartsymbols
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tasklist:
      custom_checkbox: true


plugins: []

nav:
    - Home: index.md
    - FAQ: faq.md
    - '故事': story/index.md
      - '预备': story/0_prepare.md
      - '起念': story/1_init.md
      - '进入': story/2_enter.md
      - '行进': story/3_running.md
      - '不结束': story/4_restart.md
    - '有关': about/index.md
      - '命名': about/name.md
      - '关于': about/readme.md
      #- '商标': about/brand.md
      - '资源': about/resource.md
      - '许可': about/license.md
    - '运营': scm/index.md
      - '部署': scm/deploy.md



